-- 코드를 입력하세요
SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    BOOK_SALES BS
JOIN 
    BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN 
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE 
    EXTRACT(YEAR FROM BS.SALES_DATE) = 2022
    AND EXTRACT(MONTH FROM BS.SALES_DATE) = 1
GROUP BY 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY 
    A.AUTHOR_ID ASC,
    B.CATEGORY DESC;